services:
  bot:
    container_name: cerberus-bot
    build:
      context: .
      target: production
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      MAX_BOT_TOKEN: ${MAX_BOT_TOKEN}
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  admin:
    container_name: cerberus-admin
    build:
      context: .
      target: production
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: [ "-m", "uvicorn", "admin:app", "--port", "8000", "--host", "0.0.0.0" "--proxy-headers" "--forwarded-allow-ips='*'" ]
    ports:
      - "${ADMIN_PORT:-8000}:8000"
