[project]
name = "cerberus"
version = "1.4.1"
description = "Бот учета участников Школы перед Школой и Школы Молодого Бауманца"
authors = [
    "Kirill Zhikharev"
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=26.1.0",
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "maxapi>=1.2.1",
    "psycopg2>=2.9.12",
    "punq>=0.8.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.52.3",
    "sqladmin[auth]>=0.31.0",
    "sqlalchemy>=2.0.52",
    "passlib>=1.7.4",
    "bcrypt<4.0.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
]
