name: Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
          MAX_API_TOKEN: ${{ secrets.MAX_BOT_TOKEN }}
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: POSTGRES_DSN,MAX_BOT_TOKEN
          script: |
            cd ${{ vars.PROJECT_DIR }}
            git stash
            git checkout main
            git pull origin main
            docker compose -f docker-compose.ci.yaml up --build -d
            docker system prune -f
